// <auto-generated />
using EFDemoLINQSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDemoLINQSQL.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20240417160142_CustomerDB")]
    partial class CustomerDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFDemoLINQSQL.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Budget = 10000.0,
                            CustomerName = "Doug Gegelman"
                        },
                        new
                        {
                            CustomerID = 2,
                            Budget = 20000.0,
                            CustomerName = "Liam Hutton"
                        },
                        new
                        {
                            CustomerID = 3,
                            Budget = 30000.0,
                            CustomerName = "Timothy Chesnut"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
